# Generated by Django 6.0.2 on 2026-04-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='easypaisa_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
